### ISSUE TITLE
ColoredTying: Cannot read property 'displayHexColor' of undefined

### ISSUE THREAD

**Issue by Ratismal** [DiscordInjections/Plugins#15]
@SnazzyPine25 

![a fancy screenshot](https://this.needs-to-s.top/11916b.png)

Source of error: https://github.com/DiscordInjections/Plugins/blob/master/ColoredTyping/index.js#L75

Would you like me to fix this for you?

EDIT: More context, it happens when a user is uncached, and therefore the guild object has no member object for them.

**Comment by Ratismal** [comment]
You may also want to look into this
![another screenie](https://requires.discord.gold/486ece.png)

**Comment by Snazzah** [comment]
Can you try to fix that

**Comment by Ratismal** [comment]
Done, but leaving issue open for the innerText thing

**Comment by Ratismal** [comment]
This probably isn't relevant anymore, closing
