### ISSUE TITLE
Reloading plugins with commands does not work

### ISSUE THREAD

**Issue by Martmists-GH** [DiscordInjections/Plugins#34]
Commands don't get un-registered, causing errors on reloading as it can't create commands with duplicate names.

**Comment by cyyynthia** [comment]
//reload command works for me

![](https://cdn.bowser65.tk/s/xn6mbcoA.gif)

**Comment by Ratismal** [comment]
This should be in the [main repo](https://github.com/DiscordInjections/DiscordInjections), not the plugin one.

**Comment by julien777z** [comment]
^ so TRUE
