### ISSUE TITLE
experihax machine broke

### ISSUE THREAD

**Issue by ghost** [DiscordInjections/Plugins#42]
title says all, new canary update broke it all

**Comment by cking** [comment]
not easy to fix, they rebuild the developer detection.

**Comment by ghost** [comment]
update: this code seems to work when pasted in console, when i tried editing the script, it didn't, though.

code here:
`webpackJsonp([],{d:(a,b,d)=>{let f={};for(i=0;0!==f.isDeveloper;i++)f=d(i)||{};let o=Object;o.setPrototypeOf(f,o.assign({},o.getPrototypeOf(f),{isDeveloper:1}))}},["d"]);`

**Comment by Ratismal** [comment]
Going to close this as experihax is no longer supported
