### ISSUE TITLE
Renamer using undefined classes

### ISSUE THREAD

**Issue by bytebone** [DiscordInjections/Plugins#45]
This is the errors logged in console when trying the "Local Rename" and "User Tag" function respectively:
![image](https://user-images.githubusercontent.com/18621898/29240193-136b374a-7f60-11e7-9a72-12daef6ccd7c.png)

**Comment by Ratismal** [comment]
@SnazzyPine25

**Comment by aetheryx** [comment]
ayy, I'm famous
