### ISSUE TITLE
greentext: breaks user and channel mentioning

### ISSUE THREAD

**Issue by homonovus** [DiscordInjections/Plugins#54]
### Information (fill this out)

> DI Version:  3.2.1<br>
> Plugin Name:  TelegramStickers<br>
> Author (mention them): @SnazzyPine25 

Client:
 - [x] Stable
 - [ ] PTB
 - [ ] Canary
 - [ ] Development
 
OS:
 - [x] Windows
 - [ ] Mac
 - [ ] Linux (include distro)

### Checklist

I have:
 - [x] Updated the plugin to the latest version
 - [ ] Updated DiscordInjections to the latest version
 - [ ] Checked to see if there are any existing issues open for this problem

### The Problem

Mentioning any user or channel causes the "hitbox" to be displaced to the top of the clickable area, also causes tooltips' hitbox on emoji to be displaced

### Steps to Reproduce

1. Mention any user or channel, use any emoji

### Additional Comments

it shows, but you cant click on them for their original function

**Comment by Ratismal** [comment]
@SnazzyPine25

**Comment by homonovus** [comment]
update: they show, but their "hitbox" is extremely small and at the top of the clickable area

**Comment by sylveon** [comment]
also breaks emoji name on hover

**Comment by iDerp** [comment]
It also seems to break live message edits, you have to switch to  a different channel and back to see the edited message

**Comment by homonovus** [comment]
this plugin is just broken in general lol
