### ISSUE TITLE
TelegramStickers: Instructions / Publish Links Down. Fix please

### ISSUE THREAD

**Issue by wtrflsh** [DiscordInjections/Plugins#82]

**Comment by cking** [comment]
which links?

**Comment by cking** [comment]
> https://gist.github.com/Snazzah/a3388954d5e386a35ae39d9d00962adb

@Snazzah ^

**Comment by Ratismal** [comment]
@Waterflash in the future please follow the guidelines for submitting issues.

**Comment by Snazzah** [comment]
I don't get the problem. The link works fine.

**Comment by cking** [comment]
This one works fine. Look at the one in the Readme

**Comment by wtrflsh** [comment]
@cking thx works fine now

**Comment by Snazzah** [comment]
@cking close this or riot
