### ISSUE TITLE
doesnt load (check image)

### ISSUE THREAD

**Issue by bytebone** [DiscordInjections/Plugins#88]
### Information (fill this out)

> DI Version: 3.2.2 <br>
> Plugin Name: Renamer <br>
> Author (mention them): @megamit

Client:
 - [x] Stable
 - [ ] PTB
 - [ ] Canary
 - [ ] Development
 
OS:
 - [x] Windows
 - [ ] Mac
 - [ ] Linux (include distro)

### Checklist

I have:
 - [x] Updated the plugin to the latest version
 - [x] Updated DiscordInjections to the latest version
 - [x] Checked to see if there are any existing issues open for this problem

### The Problem

it doesnt load on starting discord.

![image](https://user-images.githubusercontent.com/18621898/31861441-a0d43776-b72d-11e7-91ce-aa34792b3fd3.png)

### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. install plugin and run "npm run install-plugins"
2. start discord
3. check console

### Additional Comments

Please write down any additional comments here.

you might wanna remove the the spaces in the [] parts of the issue template because its annoying to remove them, sorry

**Comment by cking** [comment]
You need the spaces for empty boxes.

**Comment by megamit** [comment]
Some completely other dude maintains the discordinjections version of renamer

**Comment by tilda** [comment]
tagging **real** author of this version: @Snazzah

**Comment by Snazzah** [comment]
Not fixing because:
1. v4 is in beta
2. v4 handles this problem

**Comment by cking** [comment]
i assume its safe to close then. when snazzah decides to update this plugin he can post a link in here
