### ISSUE TITLE
experihax broke again, why discord devs, just why.

### ISSUE THREAD

**Issue by ghost** [DiscordInjections/Plugins#89]
### Information (fill this out)

> DI Version:  <br>3.3.0
> Plugin Name:  <br>Experihax
> Author (mention them): @Ratismal (i think)

Client:
 - [ ] Stable
 - [ ] PTB
 - [X] Canary
 - [ ] Development
 
OS:
 - [X] Windows
 - [ ] Mac
 - [ ] Linux (include distro)

### Checklist

I have:
 - [X] Updated the plugin to the latest version
 - [X] Updated DiscordInjections to the latest version
 - [X] Checked to see if there are any existing issues open for this problem

### The Problem

Please write what the problem you're having is.
it broke, it just doesn't work, _discord devs why_
### Steps to Reproduce

Please write down the steps to reproduce this problem.

1. install the plugin
2. launch discord
3. it broke

### Additional Comments

Please write down any additional comments here.

you can close this if u want i dont really care

**Comment by cking** [comment]
Look at issue #42 - experihax is unsupported and wont receive official support. PR a fix, if you are interested, but we wont be touching it.

**Comment by ghost** [comment]
that's fine, i'm just saying that it broke. @cking
